spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mariadb://74.208.33.72:63306/xpress_dinero
    username: xpress_dinero_noco
    password: x&p20q6H2
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    mongodb:
      uri: mongodb+srv://reports_xpress_user_rw:ULh0VykDvetWM3JM@cluster0.zoa5e.gcp.mongodb.net/ReportsXpress
sentry:
  dsn: https://91bb4322f0905e42c4acc5b9f3873975@o1037894.ingest.us.sentry.io/4508762622459904
  traces-sample-rate: 1.0